### ISSUE TITLE
Adding Gunblade to a boost slot throws an exception

### ISSUE THREAD

**Issue by brebory** [Zekareisoujin/MFFWeaponCalc#1] opened 2018-01-04 19:08 UTC
When adding Gunblade to a boost slot, an exception is thrown and the weapon is not successfully added:

```
calc.js:79 Uncaught TypeError: Cannot read property 'stepCounts' of undefined
    at WeaponBoostCalculator (calc.js:79)
    at WeaponSlot (weaponSlot.js:66)
    at HTMLButtonElement.addWeaponToBoostArea (index.js:61)
    at HTMLButtonElement.dispatch (jquery-3.2.1.min.js:3)
    at HTMLButtonElement.q.handle (jquery-3.2.1.min.js:3)
```

**Comment by brebory** [comment] 2018-01-04 19:17
Looks like gunblade's `ability2` of `improved_crit_30` doesn't have a matching entry.

**Comment by Zekareisoujin** [comment] 2018-01-05 11:14
Caused by missing data in the db. It is now fixed.

**Closed by Zekareisoujin** 2018-01-05 11:14 UTC
